from transformers import AutoTokenizer, AutoModelForSequenceClassification
import constants

AutoTokenizer.from_pretrained(constants.MODEL_NAME).save_pretrained(constants.DEST_PATH)
AutoModelForSequenceClassification.from_pretrained(constants.MODEL_NAME).save_pretrained(constants.DEST_PATH)